Repository simonsobs/pspy, pull requests merged in 2023-02, with the labels that each got.

#32 add option for different order for the CAR pixel window function
  pspy/so_map.py
Labels: enhancement

#33 Use latest version of versioneer and fix issue with cmdclass from numpy
  pspy/__init__.py
  pspy/_version.py
  setup.py
  versioneer.py
Labels: bug

#34 Add bot to check github actions versions
  .github/dependabot.yml
Labels: enhancement

#40 Add test and wheels for python 3.11
  .github/workflows/testing.yml
  .github/workflows/wheels.yml
Labels: enhancement

#41 Fix issue with latest versioneer version and installation of tests/data
  MANIFEST.in
  setup.py
Labels: fix
